# Generated by Django 6.0.1 on 2026-01-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_rename_idproductolaboral_productoslaborales_idproductoslaborales_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cursosrealizados',
            name='curso_totalhoras_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='cursosrealizados',
            name='curso_fechas_validas',
        ),
        migrations.RemoveConstraint(
            model_name='experiencialaboral',
            name='experiencia_fechas_validas',
        ),
        migrations.RemoveConstraint(
            model_name='ventagarage',
            name='garage_valor_gte_0',
        ),
    ]
