# Generated by Django 6.0.1 on 2026-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_cursosrealizados_curso_totalhoras_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='cursosrealizados',
            constraint=models.CheckConstraint(condition=models.Q(('fechafin__gte', models.F('fechainicio'))), name='curso_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='experiencialaboral',
            constraint=models.CheckConstraint(condition=models.Q(('fechafingestion__isnull', True), ('fechafingestion__gte', models.F('fechainiciogestion')), _connector='OR'), name='experiencia_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='ventagarage',
            constraint=models.CheckConstraint(condition=models.Q(('valordelbien__gte', 0)), name='garage_valor_gte_0'),
        ),
    ]
